spring:
  application:
    name: micro-eureka-server
server:
  port: 9001
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      default-zone: http://peer1:9000/eureka/