spring:
  application:
    name: @pom.artifactId@
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
    # 使用IP形式定义注册中心地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  server:
    enable-self-preservation: false