server:
  port: 8888

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

